- name: This sets up an httpd webserver
  hosts: aws_ec2
  become: yes
  remote_user: ec2-user
  gather_facts: true
  vars:
    ansible_ssh_private_key_file: "/etc/ansible/ansible.pem"  
    ansible_ssh_user: "ec2-user"
  tasks:
  - name: "Install httpd and php packages"
    package:
        name:
          - "httpd"
          - "php"
        state: present
  - name: "copy code from GitHub"
    get_url:
        url: https://www.shubhammishra.in
        dest: "/var/www/html/index.php"
  - name: "Start httpd services"
    service:
        name: httpd
        state: started
